### PR TITLE
BugFix: Schema date-time inputs broken

### LINKED ISSUE #10158: Unable to select correct date/time for deployment flow run parameters
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

My team is attempting to use the date selection tool to set deployment flow run parameters. The selection is not behaving as expected - the date/time being clicked isn't always what is selected, and attempting to retry by clicking the correct value is causing the other date in our params to decrement by a single day each time. The desired selected times are a week apart.

### Reproduction

https://github.com/PrefectHQ/prefect/assets/19937265/f0aef1ea-115f-4c0a-94e4-89a2b9f8b484

### Error

^ See recording in reproduction section.

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pleek91**
# Description
Closes https://github.com/PrefectHQ/prefect/issues/10158

Updates the way we're mapping, editing, and comparing dates for schemas. 

- The string property service only deals with UTC values for date and date-time formats rather than trying to account for timezones
- `date` formats no longer consider timezones
- `date-time` formats take into account the user's timezone only when displaying and inputting dates
- Fixes a bug where we were comparing mapped defaults with unmapped values when making value requests.

### CODE REVIEW

File: src/services/schemas/properties/SchemaPropertyService.ts [hunk 1]
```diff
@@ -82,13 +82,11 @@ export abstract class SchemaPropertyService {
...
   public mapRequestValue(value: SchemaValue): SchemaValue | undefined {
-    const mappedValue = this.request(value)
-
-    if (this.isDefaultValue(mappedValue)) {
+    if (this.isDefaultValue(value)) {
       return undefined
     }
 
-    return mappedValue
+    return this.request(value)
```
Comment (pleek91) [inline src/services/schemas/properties/SchemaPropertyService.ts:89]: This is where we were comparing a mapped value with an unmapped value. Most of the time that was fine because we were stringifying to compare. But comparing two unmapped values produces a more accurate comparison.

**Review by znicholasbrown — APPROVED** [review]
